/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ZustandTestRouteImport } from './routes/zustand-test'
import { Route as MswTestRouteImport } from './routes/msw-test'
import { Route as MindmapRouteImport } from './routes/mindmap'
import { Route as EmbedRouteImport } from './routes/embed'
import { Route as IndexRouteImport } from './routes/index'

const ZustandTestRoute = ZustandTestRouteImport.update({
  id: '/zustand-test',
  path: '/zustand-test',
  getParentRoute: () => rootRouteImport,
} as any)
const MswTestRoute = MswTestRouteImport.update({
  id: '/msw-test',
  path: '/msw-test',
  getParentRoute: () => rootRouteImport,
} as any)
const MindmapRoute = MindmapRouteImport.update({
  id: '/mindmap',
  path: '/mindmap',
  getParentRoute: () => rootRouteImport,
} as any)
const EmbedRoute = EmbedRouteImport.update({
  id: '/embed',
  path: '/embed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/embed': typeof EmbedRoute
  '/mindmap': typeof MindmapRoute
  '/msw-test': typeof MswTestRoute
  '/zustand-test': typeof ZustandTestRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/embed': typeof EmbedRoute
  '/mindmap': typeof MindmapRoute
  '/msw-test': typeof MswTestRoute
  '/zustand-test': typeof ZustandTestRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/embed': typeof EmbedRoute
  '/mindmap': typeof MindmapRoute
  '/msw-test': typeof MswTestRoute
  '/zustand-test': typeof ZustandTestRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/embed' | '/mindmap' | '/msw-test' | '/zustand-test'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/embed' | '/mindmap' | '/msw-test' | '/zustand-test'
  id: '__root__' | '/' | '/embed' | '/mindmap' | '/msw-test' | '/zustand-test'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EmbedRoute: typeof EmbedRoute
  MindmapRoute: typeof MindmapRoute
  MswTestRoute: typeof MswTestRoute
  ZustandTestRoute: typeof ZustandTestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/zustand-test': {
      id: '/zustand-test'
      path: '/zustand-test'
      fullPath: '/zustand-test'
      preLoaderRoute: typeof ZustandTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/msw-test': {
      id: '/msw-test'
      path: '/msw-test'
      fullPath: '/msw-test'
      preLoaderRoute: typeof MswTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mindmap': {
      id: '/mindmap'
      path: '/mindmap'
      fullPath: '/mindmap'
      preLoaderRoute: typeof MindmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/embed': {
      id: '/embed'
      path: '/embed'
      fullPath: '/embed'
      preLoaderRoute: typeof EmbedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EmbedRoute: EmbedRoute,
  MindmapRoute: MindmapRoute,
  MswTestRoute: MswTestRoute,
  ZustandTestRoute: ZustandTestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
